# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 835)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btn_com = QtWidgets.QPushButton(self.centralWidget)
        self.btn_com.setGeometry(QtCore.QRect(130, 40, 81, 41))
        self.btn_com.setObjectName("btn_com")
        self.et_com = QtWidgets.QTextEdit(self.centralWidget)
        self.et_com.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.et_com.setObjectName("et_com")
        self.et_rssi = QtWidgets.QTextEdit(self.centralWidget)
        self.et_rssi.setGeometry(QtCore.QRect(240, 10, 91, 41))
        self.et_rssi.setObjectName("et_rssi")
        self.cb_rssi = QtWidgets.QCheckBox(self.centralWidget)
        self.cb_rssi.setGeometry(QtCore.QRect(360, 5, 71, 41))
        self.cb_rssi.setObjectName("cb_rssi")
        self.et_devname = QtWidgets.QTextEdit(self.centralWidget)
        self.et_devname.setGeometry(QtCore.QRect(460, 10, 111, 41))
        self.et_devname.setObjectName("et_devname")
        self.cb_devname = QtWidgets.QCheckBox(self.centralWidget)
        self.cb_devname.setGeometry(QtCore.QRect(590, 20, 91, 21))
        self.cb_devname.setObjectName("cb_devname")
        self.btn_conn_state = QtWidgets.QPushButton(self.centralWidget)
        self.btn_conn_state.setGeometry(QtCore.QRect(810, 20, 81, 31))
        self.btn_conn_state.setObjectName("btn_conn_state")
        self.btn_disconnect = QtWidgets.QPushButton(self.centralWidget)
        self.btn_disconnect.setGeometry(QtCore.QRect(240, 80, 101, 41))
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.btn_next = QtWidgets.QPushButton(self.centralWidget)
        self.btn_next.setGeometry(QtCore.QRect(380, 80, 111, 41))
        self.btn_next.setObjectName("btn_next")
        self.tv_log = QtWidgets.QTextBrowser(self.centralWidget)
        self.tv_log.setGeometry(QtCore.QRect(20, 160, 561, 341))
        self.tv_log.setObjectName("tv_log")
        self.btn_acc = QtWidgets.QPushButton(self.centralWidget)
        self.btn_acc.setGeometry(QtCore.QRect(40, 690, 101, 41))
        self.btn_acc.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_acc.setObjectName("btn_acc")
        self.btn_gyr = QtWidgets.QPushButton(self.centralWidget)
        self.btn_gyr.setGeometry(QtCore.QRect(180, 690, 101, 41))
        self.btn_gyr.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_gyr.setObjectName("btn_gyr")
        self.btn_cps = QtWidgets.QPushButton(self.centralWidget)
        self.btn_cps.setGeometry(QtCore.QRect(310, 690, 121, 41))
        self.btn_cps.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_cps.setObjectName("btn_cps")
        self.btn_sn = QtWidgets.QPushButton(self.centralWidget)
        self.btn_sn.setGeometry(QtCore.QRect(470, 690, 111, 41))
        self.btn_sn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_sn.setObjectName("btn_sn")
        self.btn_mac = QtWidgets.QPushButton(self.centralWidget)
        self.btn_mac.setGeometry(QtCore.QRect(640, 690, 141, 51))
        self.btn_mac.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_mac.setObjectName("btn_mac")
        self.et_snmac = QtWidgets.QTextEdit(self.centralWidget)
        self.et_snmac.setGeometry(QtCore.QRect(30, 580, 541, 51))
        self.et_snmac.setObjectName("et_snmac")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(50, 540, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(40, 660, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(180, 660, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(320, 660, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(480, 660, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(660, 660, 54, 12))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1115, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_com.setText(_translate("MainWindow", "打开"))
        self.cb_rssi.setText(_translate("MainWindow", "Rssi"))
        self.cb_devname.setText(_translate("MainWindow", "过滤设备名"))
        self.btn_conn_state.setText(_translate("MainWindow", "连接状态"))
        self.btn_disconnect.setText(_translate("MainWindow", "断开连接"))
        self.btn_next.setText(_translate("MainWindow", "继续"))
        self.btn_acc.setText(_translate("MainWindow", "OK"))
        self.btn_gyr.setText(_translate("MainWindow", "OK"))
        self.btn_cps.setText(_translate("MainWindow", "OK"))
        self.btn_sn.setText(_translate("MainWindow", "OK"))
        self.btn_mac.setText(_translate("MainWindow", "OK"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">串口号</p></body></html>"))
        self.label.setText(_translate("MainWindow", "SN/MAC"))
        self.label_2.setText(_translate("MainWindow", "加速度传感器"))
        self.label_3.setText(_translate("MainWindow", "陀螺仪"))
        self.label_4.setText(_translate("MainWindow", "地磁"))
        self.label_5.setText(_translate("MainWindow", "SN"))
        self.label_6.setText(_translate("MainWindow", "MAC"))

